source_path: "/mnt/media3/porn/Adult/B"
# dest_path: "/mnt/media3/porn/temp/working/"
staging_path: "/mnt/media3/porn/temp/Staging/"
trash_path: "/mnt/media3/porn/temp/Staging/trash/"
handbrake_path: "/mnt/media3/Multimedia/decoder/HandBrake/build/"
ffmpeg_path: ""

# Optional values can be commented out
# bitrate: 1000
# src_bitrate: 900
# maxrate: 1500
# bufsize: 3000
extensions_vector: ".mp4,.avi,.mkv"
encoder: "nvenc"
codec: "h264"
preset: ""
encoder_type: "ffmpeg"
extension: "mp4"
converted_string: "converted"
# audio_encode: "-c:a aac -q:a 100"
multi_pass: 0
crf: 34
addon: ""
max_size: 0
consolidate: 1
error_logging: 0

# scale: "w=854:h=480"